server:
  host: 127.0.0.1
  llmPort: 8080
  adminPort: 3001
  uiPort: 3000
  adminApiKey: ${ADMIN_API_KEY}

clients:
  - id: claude-cli
    apiKey: ${CLIENT_KEY_CLAUDE}
  - id: kilo
    apiKey: ${CLIENT_KEY_KILO}

providers:
  anthropic:
    type: anthropic
    apiKey: ${ANTHROPIC_API_KEY}
    baseURL: https://api.anthropic.com/v1

  openai:
    type: openai
    apiKey: ${OPENAI_API_KEY}
    baseURL: https://api.openai.com/v1

  lmstudio:
    type: openai
    apiKey: "UNNECESSARY"
    baseURL: http://localhost:1234

  openrouter:
    type: openai
    apiKey: ${OPEN_ROUTER_API_KEY}
    baseURL: https://openrouter.ai/api

  copilot-openai:  # See https://github.com/shyamsridhar123/ClaudeCode-Copilot-Proxy
    type: openai
    apiKey: "sk-dummy"
    baseURL: http://localhost:4141/

  copilot-anthropic:  # See https://github.com/shyamsridhar123/ClaudeCode-Copilot-Proxy
    type: anthropic
    apiKey: "sk-dummy"
    baseURL: http://localhost:4141/

  kilo:
    type: openai
    apiKey: ${KILO_API_KEY}
    baseURL: https://api.kilo.ai/api/gateway

  brad:
    type: anthropic
    apiKey: ${BRAD_API_KEY}
    baseURL: https://racecar.diskstation.me:1234

modelRouting:
# OpenRouter
  - name: free-random
    provider: openrouter
    model: openrouter/free
  - name: free-high
    provider: openrouter
    model: stealth/ox-alpha
  - name: free-medium
    provider: openrouter
    model: nvidia/nemotron-3.5-lightning:free

# Claude
  - name: claude-3-5-sonnet-latest
    provider: anthropic
    model: claude-3-5-sonnet-20241022
  - name: claude-3-5-haiku-latest
    provider: anthropic
    model: claude-3-5-haiku-20241022
  - name: gpt-4o
    provider: openai
    model: gpt-4o

# Copilot
  - name: copilot-sonnet-5
    provider: copilot-anthropic
    model: claude-sonnet-5

  - name: copilot-gemini-flash-3.8
    provider: copilot-openai
    model: gemini-3.8-flash

  - name: copilot-gpt-5.4-mini
    provider: copilot-openai
    model: gpt-5.4-mini

#  Local
  - name: local
    provider: lmstudio
    model: available

# Claude-requested
  - name: claude-haiku-*
    provider: openrouter
    model: poolside/laguna-s-2.1:free

# Kilo
  - name: kilo-auto
    provider: kilo
    model: kilo-auto/free
  - name: kilo-frontier # Paid only
    provider: kilo
    model: kilo-auto/frontier
  - name: kilo-balanced
    provider: kilo
    model: kilo-auto/balanced
  - name: kilo-efficient
    provider: kilo
    model: kilo-auto/efficient

# Brad
  - name: brad-high
    provider: brad
    model: "qwen3.8-27b:mtp-q4_k_m-175k"

  - name: brad-low
    provider: brad
    model: "qwen3.5-9b:q4_k_m"

sessions:
  file: sessions.json
