server:
  host: 127.0.0.1
  llmPort: 8080
  adminPort: 3001
  uiPort: 3000
  adminApiKey: ${ADMIN_API_KEY}

clients:
  - id: claude-cli
    apiKey: ${CLIENT_KEY_CLAUDE}
  - id: kilo
    apiKey: ${CLIENT_KEY_KILO}

providers:
  anthropic:
    type: anthropic
    apiKey: ${ANTHROPIC_API_KEY}
    baseURL: https://api.anthropic.com/v1

  openai:
    type: openai
    apiKey: ${OPENAI_API_KEY}
    baseURL: https://api.openai.com/v1

  lmstudio:
    type: openai
    apiKey: "UNNECESSARY"
    baseURL: http://localhost:1234

  openrouter:
    type: openai
    apiKey: ${OPEN_ROUTER_API_KEY}
    baseURL: https://openrouter.ai/api

  copilot:  # See https://github.com/shyamsridhar123/ClaudeCode-Copilot-Proxy
    type: anthropic
    apiKey: "sk-dummy"
    baseURL: http://localhost:3000/

  kilo:
    type: openai
    apiKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbnYiOiJwcm9kdWN0aW9uIiwia2lsb1VzZXJJZCI6IjczOWMxMWE2LTQ0OGMtNDBlYy1hYWYyLTVjNWQ5NDFhNWNhOSIsImFwaVRva2VuUGVwcGVyIjpudWxsLCJ2ZXJzaW9uIjozLCJpYXQiOjE3ODc1MTc5NzMsImV4cCI6MTk0NTE5Nzk3M30.Fd8J7AQcky1c05W-ibUBjkeB3oTuadpy3Ezja6oAZvc"
    baseURL: https://api.kilo.ai/api/gateway

modelRouting:
# OpenRouter
  - name: free-random
    provider: openrouter
    model: openrouter/free
  - name: free-high
    provider: openrouter
    model: stealth/ox-alpha
  - name: free-medium
    provider: openrouter
    model: nvidia/nemotron-3.5-lightning:free

# Claude
  - name: claude-3-5-sonnet-latest
    provider: anthropic
    model: claude-3-5-sonnet-20241022
  - name: claude-3-5-haiku-latest
    provider: anthropic
    model: claude-3-5-haiku-20241022
  - name: gpt-4o
    provider: openai
    model: gpt-4o

# Copilot
  - name: copilot
    provider: copilot
    model: auto

#  Local
  - name: local
    provider: lmstudio
    model: available

# Claude-requested
  - name: claude-haiku-*
    provider: openrouter
    model: poolside/laguna-s-2.1:free

# Kilo
  - name: kilo-auto
    provider: kilo
    model: kilo-auto/free
  - name: kilo-frontier # Paid only
    provider: kilo
    model: kilo-auto/frontier
  - name: kilo-balanced
    provider: kilo
    model: kilo-auto/balanced
  - name: kilo-efficient
    provider: kilo
    model: kilo-auto/efficient

    


sessions:
  file: sessions.json
